/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    'Play': '开始',
    'I didn\'t know what to call the game.': '我不知道该怎么称呼这个游戏。',
    'Gains some free power every roll.': '每轮获得一些免费的力量',
    'Better': '更好',
    'Blue': '蓝色',
    'Blue Angel': '蓝天使',
    'Experience points': '经验值',
    'experience points': '经验值',
    'Efficient': '高效',
    'First Step': '第一步',
    'Free Die': '免费骰子',
    'From now on you start with an extra die.': '从现在开始，您将从额外的骰子开始。',
    'Endless Combo': '无尽的组合',
    'Free Gold': '免费的黄金',
    'The last ones are music and can take awhile!': '最后一个是音乐，可能需要一段时间加载！',
    'The last sounds take a while to load, it\'s the music!': '最后的声音加载需要一段时间，这是音乐！',
    'The logo above is the only image in the game.  I can\'t draw for beans.': '上面的徽标是游戏中唯一的图像。 我不能画豆子。',
    'This is the second game I\'ve ever released, and though it\'s a silly, simple grinder, I\'m really proud of how it turned out.  Please leave a comment if you can!  Positive or negative, I\'ll use it to make my next game even better!': '这是我发布的第二款游戏，尽管它是一款愚蠢而简单的研磨机，但我对它的结果感到非常自豪。 如果可以，请发表评论！ 积极或消极，我会用它来让我的下一款游戏更好！',
    'This game isn\'t in flash.  HTML5 magic!': '这个游戏不是Flash制作的。 是HTML5魔法！',
    'Save Game': '保存游戏',
    'Sprint': '短跑',
    'Too Easy?': '太简单？',
    'Turn': '回合',
    'Yellow': '黄色',
    'Purchase New Die [P]': '购买新骰子 [P]',
    'Quarters': '住处',
    'Roll': '投掷',
    'Rolls Left': '剩余投掷次数',
    'Green Angel': '绿天使',
    'Hide Earned': '隐藏获得',
    'Hide Mastered': '隐藏专精',
    'Highest Magic': '最高魔法',
    'Level': '等级',
    'Yay [R]': '耶 [R]',
    'gold.': '黄金。',
    'Good': '不错',
    'Great': '很好',
    'Game Over!': '游戏结束!',
    'Gates': '大门',
    'Getting Close': '越来越接近',
    'Gold Earned': '赚取的黄金',
    'You are out of turns!  Game over!': '你出局了！ 游戏结束！',
    'You can earn perks by levelling up from experience points, mastering tricks, or completing achievements.': '您可以通过升级经验值，掌握技巧或完成成就来获得额外收入。',
    'You can move this window around at any time.': '您可以随时移动此窗口。',
    'You can start a new game, and keep your levels and perks.': '你可以开始一个新的游戏，并保持你的等级和特权。',
    'You Love Logistics': '你喜欢物流',
    'You keep your XP when you start a new game.\n               ': '当你开始新游戏时，你会保留你的经验值。',
    'You Win The Game': '你赢得了比赛',
    'You Win The Game More': '你赢得了更多比赛',
    'Your dice are on the left, and you can click them to upgrade, once you have some cash.': '你的骰子在左边，一旦你有现金，你可以点击它们升级。',
    'Your highest gold-earning turn was': '你获得的最高收益是',
    'upgrade it': '升级它',
    'Tricks Learned': '学会的技巧',
    'Tricks Mastered: ': '精通的技巧：',
    'Tricks Performed': '执行的技巧',
    'Tricks Performed (this game': '执行的技巧（本轮游戏',
    'money': '金钱',
    'Morning': '早上',
    'New Game +': '新游戏 +',
    'Okay': '好的',
    'Options': '选项',
    'Game saves automatically after every roll.  This button is for the paranoid.': '每次投掷后游戏都会自动保存。 这个按钮适合偏执狂。',
    'Gold Earned (this game': '赚取的黄金（本轮游戏',
    'Start a new game with all your xp and levels.': '用你所有的经验和等级开始一个新的游戏。',
    "Power: Increases the power of your die.  Each step of power increases the number of sides (and therefore the maximum roll).  When it gets big enough, it resets down to a smaller size, but gains a point of Magic (": "力量：增加你的骰子的力量。 功率的每一步都会增加边数（因此会增加投掷上限）。 当它变得足够大时，它会重置为更小的尺寸，但会获得一点魔法值（",
    "BP:": "奖励分：",
    "Bonus points": "奖励分",
    "bonus points": "奖励分",
    ") for the": ") ",
    "XP:": "经验:",
    ", if you've bought that trick.": "，如果你买了那个把戏。",
    ", plus": ", 加上",
    ", plus an extra 1x those earnings (": "，再加上这些收入的 1 倍（",
    ", which add bonus turns.": "，这会增加奖励回合。",
    ": Earns": ": 赚",
    ": Earns much more": ": 赚了",
    ": Gains some free power every roll.": "：每次投掷获得一些自由力量。",
    ": Increases its own multiplier with each roll.": "：每次掷骰都会增加自己的乘数。",
    ": Increases the multiplier of every other die each roll.": "：增加每次投掷每个其他骰子的乘数。",
    "are for extra turns.": "用于额外转弯。",
    "are for levels.  Levels give you bonuses.": "是为了等级。 升级会给你奖励。",
    "are special \"moves\" you can do, like getting One Pair of the same number in one roll, or Three of a Kind.": "是您可以做的特殊“动作”，例如在一次投掷中获得相同数字的一对，或三种。",
    "Click": "点击",
    "Click a die on the left to": "点击左边的骰子",
    "Don't be discouraged when you lose!": "输的时候不要气馁！",
    "Dunno": "Dunno",
    "Dunno is a game about rolling dice and making money.  Try to make as much money as you can in a limited number of turns.": "Dunno 是一款关于掷骰子和赚钱的游戏。 尝试在有限的回合数内赚取尽可能多的钱。",
    "Each extra turn costs more.": "每多转一圈花费更多。",
    "Example die rolls:": "掷骰子示例：",
    "for": "为了",
    "for the pair of 2s, plus": "对于一对 2，加上",
    "for the pair of 3s, PLUS": "对于一对 3s，加上",
    "Gold": "金币",
    "Gold:": "金币：",
    "Green": "绿色",
    "If you skip the tutorial, you can click Help at any time.": "如果您跳过教程，您可以随时单击“帮助”。",
    "is for buying dice, upgrading dice, and buying tricks.": "用于购买骰子、升级骰子和购买技巧。",
    "keep all your perks.": "保留所有特权。",
    "Level:": "等级：",
    "Magic: Spend the Magic points gained from Power to add something new to the die, depending on the color.  Each color does something different!": "魔法：花费从能量中获得的魔法点数来为骰子添加新的东西，具体取决于颜色。 每种颜色都有不同的作用！",
    "Most dice award you money when you roll them.": "大多数骰子在您掷骰子时都会奖励您金钱。",
    "Multiple stars of the same color stack, increasing the effect!": "多颗同色星星叠加，增加效果！",
    "Multiplier: Multiplies the earnings of the die.": "乘数：乘以骰子的收益。",
    "On the right are the tabs where you'll control the game.": "右侧是您控制游戏的选项卡。",
    "One Pair": "一对",
    "pane.  There, click": "窗格。 在那里，点击",
    "Perks are special bonuses that you keep when you play the game again.": "特权是您再次玩游戏时保留的特殊奖励。",
    "Pink": "粉色",
    "Purple": "紫色",
    "Red": "红色",
    "Rolling your dice gives you stuff!": "掷骰子给你东西！",
    "Rolls Left:": "剩余投掷次数：",
    "Stacks with": "堆栈与",
    "Thanks for playing!": "感谢参与！",
    "That means the next time through will be easier and faster, especially after the first time.": "这意味着下一次通过将更容易和更快，尤其是在第一次之后。",
    "That's it!": "就是这样！",
    "to roll the dice you have.": "掷骰子。",
    "to see the": "看到",
    "to see the Perks you've gained from levelling up so far.": "查看到目前为止您升级所获得的额外特权。",
    "to see the tricks you have.  You start with": "看看你有什么技巧。 你开始",
    "trick.": "诡计。",
    "tricks": "技巧",
    "Tricks": "技巧",
    "Tricks are mastered by performing them repeatedly.  Mastering tricks can unlock new ones!": "技巧是通过反复表演来掌握的。 掌握技巧可以解锁新技巧！",
    "Tricks usually grant you a bonus on top of what the matching dice give.  Click next to learn more.": "技巧通常会在匹配骰子给予的奖励之上为您提供奖励。 单击下一步以了解更多信息。",
    "Two Pair": "两对",
    "Welcome to Dunno!": "欢迎来到不知道！",
    "When you run out of turns, you can start over but you": "当你用完转弯时，你可以重新开始，但你",
    "You get these with Blue dice (explained later).": "你用蓝色骰子得到这些（稍后解释）。",
    "You keep your XP when you start a new game.": "当您开始新游戏时，您会保留 经验值。",
    "Abracadabra": "胡言乱语",
    "Achievements Earned:": "取得的成就：",
    "Alakazam": "阿拉卡赞",
    "Amazing": "惊人的",
    "Apprentice": "学徒",
    "Archmage": "大法师",
    "Awesome": "惊人的",
    "Back": "后退",
    "Billions of Billions": "数十亿",
    "Blue Apprentice": "蓝色学徒",
    "Blue BPs Earned": "获得的蓝色 BP",
    "Blue BPs Earned:": "获得的蓝色 BP：",
    "Blue Demon": "蓝色恶魔",
    "Blue Grandmaster": "蓝色宗师",
    "Blue Journeyman": "蓝色熟练工",
    "Blue Mage": "蓝色法师",
    "Blue Master": "蓝色大师",
    "Blue Wizard": "蓝色巫师",
    "C-c-combo": "C-c-组合",
    "C-c-combo Breaker!": "C-c-组合断路器！",
    "C-combo": "C组合",
    "close": "关闭",
    "Combo": "组合",
    "Combo of Combos": "组合的组合",
    "Comboception": "组合感受",
    "Created with Raphaël 2.1.0": "使用 Raphaël 2.1.0 创建",
    "Dawn": "黎明",
    "Dice Purchased:": "购买的骰子：",
    "Dice Rolled": "掷骰子",
    "Dice Rolled (this game):": "掷骰子（本游戏）：",
    "Dice Rolled:": "掷骰子：",
    "Dimes": "角钱",
    "Dollars": "美元",
    "Earn a little gold, experience, and bonus points based on your die rolls.": "根据您的掷骰结果赚取一点金币、经验和奖励点数。",
    "Exponential": "指数型",
    "ghijkl": "吉克尔",
    "Gold Earned (this game):": "获得的金币（本场比赛）：",
    "Gold Earned:": "金币获得：",
    "Golden Parachute": "金色降落伞",
    "Green Apprentice": "绿色学徒",
    "Green Demon": "绿魔",
    "Green Grandmaster": "绿色宗师",
    "Green Journeyman": "绿色熟练工",
    "Green Mage": "绿色法师",
    "Green Master": "绿色大师",
    "Green Power Gained": "获得绿色力量",
    "Green Power Gained:": "获得绿色力量：",
    "Green Wizard": "绿色巫师",
    "Highest Magic:": "最高魔法：",
    "Highest Multiplier": "最高乘数",
    "Highest Multiplier:": "最高乘数：",
    "How?": "如何？",
    "Inefficient": "低效",
    "Inspired by jmtb02.": "灵感来自 jmtb02。",
    "Jogging": "跑步",
    "Largest Die Rolled:": "掷出的最大骰子：",
    "Like a Real Incremental": "像一个真正的增量",
    "Mage": "法师",
    "Magical": "神奇",
    "Mecca Lecca Hi": "麦加 Lecca 嗨",
    "Middle Class": "中产阶级",
    "Midnight": "午夜",
    "Minor Diety": "小节食",
    "Most Dice Rolled (one game):": "大多数掷骰子（一场比赛）：",
    "Most dice rolled:": "大多数骰子掷出：",
    "Most Gold Earned (one game)": "获得最多金币（一场比赛）",
    "Most Gold Earned (one game):": "获得最多金币（一场比赛）：",
    "Most Gold in One Turn": "一回合最多金币",
    "Most Gold in One Turn:": "一回合最多金币：",
    "Most Tricks in One Turn": "一回合内最多的技巧",
    "Most Tricks in One Turn:": "一回合最多技巧：",
    "Most Tricks Performed (one game):": "大多数技巧表演（一场比赛）：",
    "Most Turns Taken (one game):": "大多数回合（一场比赛）：",
    "Next": "下一个",
    "Noon": "中午",
    "Pennies": "便士",
    "Pink Angel": "粉红天使",
    "Pink Apprentice": "粉红学徒",
    "Pink Demon": "粉红恶魔",
    "Pink Grandmaster": "粉红宗师",
    "Pink Journeyman": "粉红熟练工",
    "Pink Mage": "粉红法师",
    "Pink Master": "粉红大师",
    "Pink Multiplier Gained": "获得粉色乘数",
    "Pink Multiplier Gained:": "获得粉色乘数：",
    "Pink Wizard": "粉色巫师",
    "Poor": "贫穷的",
    "Prudent": "谨慎",
    "Purple Angel": "紫天使",
    "Purple Apprentice": "紫色学徒",
    "Purple Demon": "紫色恶魔",
    "Purple Grandmaster": "紫色宗师",
    "Purple Journeyman": "紫色熟练工",
    "Purple Mage": "紫色法师",
    "Purple Master": "紫色大师",
    "Purple Wizard": "紫色巫师",
    "Purple XP Earned": "获得的紫色 经验",
    "Purple XP Earned:": "获得的紫色 经验：",
    "Ransom Money": "赎金",
    "RAWHIDE!": "生皮！",
    "Red Angel": "红色天使",
    "Red Apprentice": "红色学徒",
    "Red Demon": "红色恶魔",
    "Red Grandmaster": "红色宗师",
    "Red Journeyman": "红色熟练工",
    "Red Mage": "红色法师",
    "Red Master": "红色大师",
    "Red Multiplier Gained": "获得红色乘数",
    "Red Multiplier Gained:": "获得红色乘数：",
    "Red Wizard": "红色巫师",
    "Red/Pink Multiplier Gained:": "获得红色/粉色乘数：",
    "Rich": "富有",
    "Roll 2 of a kind.": "2 个相同的数字。",
    "Roll All the Dice!": "骰子！",
    "Roll ALL The Dice?": "所有骰子？",
    "Roll Up In Da Club?": "加入 Da Club？",
    "Roll!": "掷骰子！",
    "Rolls Royce": "劳斯莱斯",
    "Running": "跑步",
    "Salary": "薪水",
    "Shazam": "沙赞",
    "Sim Sala Bim": "辛萨拉宾",
    "START COMPLETELY OVER": "重新开始",
    "Tada": "多田",
    "This is a pane for perks.": "这是特权的窗格。",
    "Times Tabler": "泰晤士报",
    "Tricks Learned:": "学到的技巧：",
    "Tricks Mastered:": "掌握的技巧：",
    "Tricks Performed (this game):": "表演技巧（本场比赛）：",
    "Tricks Performed:": "表演技巧：",
    "Turns Taken": "轮流采取",
    "Turns Taken (this game):": "回合数（本场比赛）：",
    "Turns Taken:": "回合数：",
    "Voila": "瞧",
    "Walking": "步行",
    "Wealthy": "富裕",
    "Weighted Dice": "加权骰子",
    "Welcome to Dunno": "欢迎来到 Dunno",
    "White XP Earned:": "获得的白色 经验：",
    "Wizard": "巫师",
    "Wow Such Cash": "哇这么多钱",
    "x the earnings of every die.": "x 每个骰子的收益。",
    "x the earnings of the matching die.": "x 匹配骰子的收益。",
    "Yellow Angel": "黄天使",
    "Yellow Apprentice": "黄色学徒",
    "Yellow Bonus Gold": "黄色奖金金",
    "Yellow Bonus Gold:": "黄色奖金金：",
    "Yellow Demon": "黄色恶魔",
    "Yellow Grandmaster": "黄色宗师",
    "Yellow Journeyman": "黄色熟练工",
    "Yellow Mage": "黄色法师",
    "Yellow Master": "黄色大师",
    "Yellow Wizard": "黄色巫师",
    "-- Gain": "-  获得",
    "by increasing Power.": "通过增加功率。",
    "Earns bonus points (for extra turns).": "赚取奖励点数（额外回合）。",
    "Earns experience points.": "获得经验值。",
    "Earns extra gold.": "赚取额外的金币。",
    "Gains power every turn.": "每回合获得力量。",
    "Increases the multiplier of all other dice each turn.": "每回合增加所有其他骰子的乘数。",
    "Increases the multiplier of this die each turn.": "每回合增加该骰子的乘数。",
    "Magic:": "魔法：",
    "Multiplier": "乘数",
    "Next die": "下一个骰子",
    "Power": "力量",
    "Prev die": "上一个骰子",
    "Shift-click": "按住 Shift 单击",
    "Sides": "双方",
    "to select a range of dice.": "选择一系列骰子。",
    "All": "全部",
    "But you can start again,": "但你可以重新开始，",
    "Don't worry, it gets easier quick.": "别担心，很快就会变得更容易。",
    "keeping all your perks and achievements": "保留您所有的特权和成就",
    "Not yet": "还没有",
    "Roll Total": "总数",
    "tricks)": "技巧）",
    "You ran out of turns!": "你用完了回合！",
    "You were pretty close to getting:": "你非常接近获得：",
    "Your highest gold-earning turn was:": "你最高的金币收入是：",
    "You have learned the Ace trick.": "你已经学会了 Ace 技巧。",
    "Free Multiplier": "免费乘数",
    "Free Power": "免费力量",
    "Micro-fib": "Micro-fib",
    "You have learned the Dueces trick.": "你已经学会了 决斗 技巧。",
    "You have learned the Micro-fib trick.": "你已经学会了 Micro-fib 技巧。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Loading sound ": "音频文件加载中...",
    "From now on you start with an extra $": "从现在开始，您初始将获得额外的 $",
    "Level ": "等级 ",
    "Turns Taken: ": "回合代币：",
    "Dice Rolled: ": "掷出的骰子：",
    "Gold Earned: ": "获得的金币：",
    "Highest Magic: ": "最高魔法：",
    "Tricks Performed: ": "执行的技巧：",
    "Roll ": "掷出 ",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    ": You gain": ": 你获得了",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 巫师'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^From now on your dice start with (.+) extra multiplier.$/, '从现在开始，您的骰子开始时会有 $1 额外乘数。'],
    [/^From now on your dice start with (.+) extra power point.$/, '从现在开始，您的骰子开始时会有 $1 力量点数。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 巫师'],
    [/^\+([\d\.]+) for \$([\d\.]+)$/, '+$1 成本 \$ $2'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 巫师'],
    [/^([\d\.,]+)XP$/, '$1 经验'],
    [/^([\d\.,]+) elves$/, '$1 巫师'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 巫师'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 巫师'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);